steps:
  - label: "🔎"
    command: go test ./...
    plugins:
      - golang#v2.0.0:
          version: 1.16.2
          import: github.com/buildkite/ecs-run-task
          environment:
            - GO111MODULE=on

  - label: "🛠"
    plugins:
      - golang-cross-compile#v1.3.0:
          build: "."
          import: github.com/buildkite/ecs-run-task
          targets:
            - version: 1.16.2
              goos: linux
              goarch: amd64
              gomodule: "on"
            - version: 1.16.2
              goos: windows
              goarch: amd64
              gomodule: "on"
